version: '3.8'
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    command: ["mongod", "--replSet", "my-replica-set", "--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5


  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["mongod", "--replSet", "my-replica-set", "--bind_ip_all"]
    ports:
      - "27018:27017"

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["mongod", "--replSet", "my-replica-set", "--bind_ip_all"]
    ports:
      - "27019:27017"

  # The setup container runs once, initializes the set, then exits
  mongo-init:
    image: mongo:7.0
    depends_on:
      mongo1:
        condition: service_healthy
    entrypoint: [ "mongosh", "--host", "mongo1", "--eval", "rs.initiate({_id: 'my-replica-set', members: [{_id: 0, host: 'mongo1:27017'}, {_id: 1, host: 'mongo2:27017'}, {_id: 2, host: 'mongo3:27017'}]})"]